SET STATISTICS TIME ON;
SET STATISTICS IO ON;

--Estimate Plan Text
SET SHOWPLAN_ALL ON;
SET SHOWPLAN_ALL OFF;

SET SHOWPLAN_TEXT ON;
SET SHOWPLAN_TEXT OFF;

--Actual Plan Text
SET STATISTICS PROFILE ON;
SET STATISTICS PROFILE OFF;

--XML Plan
SET STATISTICS XML ON;
SET STATISTICS XML OFF;

SET STATISTICS TIME OFF;
SET STATISTICS IO OFF;